### ISSUE TITLE
Access Denied error in Section 5: Medical Imaging Toolbox

### ISSUE THREAD

**Issue by markjschmidt** [Mayo-Radiology-Informatics-Lab/MIDeL#17]
When running section 1.4      # Downloading the zip archive containing sample images, 
get error:

Access denied with the following error:
unzip:  cannot find or open Sampledata_5A.zip, Sampledata_5A.zip.zip or Sampledata_5A.zip.ZIP.

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

FileNotFoundError: [Errno 2] No such file or directory: 'Sampledata_5A.zip'

**Comment by BardiaKh** [comment]
Thank you for bringing this to our attention. We have fixed the access issue, and it should work now.
I will close this issue, but feel free to re-open it if the issue still persists on your side.
